services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    networks:
      - dockernet

networks:
    dockernet: